### ISSUE TITLE
How to build in VS2017 15.5/15.6 ?

### ISSUE THREAD

**Issue by drehren** [tfennel/desktop-toasts#8]
Hi!

I'm trying to build the sample but got a lot of errors... Which VS components should I install?

Thanks

**Comment by nelis249** [comment]
I used VS2017. Make sure to have the Universal Windows Development stuff installed.

**Comment by drehren** [comment]
Are those in nuget packages?
Well I got errors for the CPP-WRL sample.
`MakeAndInitialize<XmlDocument>(&answer);` seemed to me that was the culprit.

**Comment by tantaijin** [comment]
I also got this error in vs2015, do you known how to fix it now?
The error is: error C2139: 'ABI::Windows::UI::Notifications::ToastNotification': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_base_of'
